---
title: "Comparison of descriptors between pilot data and Alon's experiment (V1)"
subtitle: "Pilot Analysis - `r format(Sys.time(), '%d %B, %Y')`"
geometry: left=2cm,right=2cm,top=2cm,bottom=2cm
output:
  pdf_document:
    latex_engine: xelatex
  html_document:
    df_print: paged
header-includes: \usepackage{xcolor}
---

```{r include=FALSE}
source('embed_import_libraries.R')
source('embed_configuration.R')

# Functions
source('function-get_image_by_id.R')
source('function-load_alon_descriptors.R')
source('function-load_pilot_data.R')
source('function-plot_image_result.R')
source('function-plot_KL_divergence.R')
source('function-plot_word_cloud.R')
source('function-print_common_words.R')
```

```{r read-summary-df-file, echo=FALSE, message=FALSE, include = FALSE, warning=FALSE}
# included_participants <- c(included_v0_lab_participants, included_v1_mturk_participants)
# full_raw_df <- load_pilot_data(summary_file, details_file, included_all_participants, by_subject = TRUE)
# full_raw_df$soa = as.factor(full_raw_df$soa)
# 
# full_df <- copy(full_raw_df) # This will be manipulated by reference so reassign to another variable.
# all_df <- unique(full_df[, `:=`(frequency = sum(frequency), confidence = mean(confidence)),
#                   by = c("img", "soa", "word", "img_id")][,-c("subject")])

# Use test_df below to sanity check/cross-check all_df - assert(test_df == all_df)
#test_df <- load_pilot_data(summary_file, details_file, included_all_participants, by_subject = FALSE)
```

```{r merge-alon-data, warning=FALSE, message=FALSE, echo=FALSE, include=FALSE}
# alon_img_desc <- load_alon_descriptors(alon_present_words, alon_subject_descriptions, alon_remove_words)
# master_raw_df <- merge(full_raw_df, alon_img_desc, by = c("img_id", "soa", "subject", "word", "frequency"), all = TRUE)[,-c("img")]

# save(included_participants, full_raw_df, full_df, all_df, alon_img_desc, master_raw_df, file="pilot_all.RData")
#alon_img_desc <- alon_img_desc[frequency > 1]
```

```{r load-variables-from-file-instead, echo=FALSE}
load(file = 'pilot_all.RData')
```

## Experiment Configuration Details
```{r print out configuration details for report, echo = FALSE, message=TRUE}
print(paste0("Summary file processed: ", summary_file))
print(paste0("Details file processed: ", details_file))
print(paste0("Included participants: (N=", length(included_participants), ")"))
```
```{r ggplot exploratory analysis, warning=TRUE, message=FALSE, echo = FALSE}
ggtitleimg <- function(title, imgid) {
  return(ggtitle(paste0(title, ' (Image ', imgid, ')')))
}

master_raw_df$soa <- factor(master_raw_df$soa, levels=c("67", "133", "267", "Unlimited"))

# Filter to only images that we are interested (20 images in pilot + 3 practice images)
included_img_ids = c(3, 9, 14, 104, 277, 321, 570, 774, 1078, 1445, 1684, 1715, 1758, 2033, 2164, 2537, 2667, 2769, 3279, 6806, 7360, 8858, 8876)
master_raw_df <- master_raw_df[img_id %in% included_img_ids]

img_soa_total_subjects <- unique(master_raw_df[, .(img_id, soa, subject)])[, .(total_subjects = .N), by = c("img_id", "soa")]
img_soa_total_non_unique_words <- master_raw_df[, .(total_words = .N), by = c("img_id", "soa")]
img_soa_total_unique_words <- unique(master_raw_df[, .(unique_words = .N), by = c("img_id", "soa", "word")])[, .(total_unique_words = .N), by = c("img_id", "soa")]
merge_img_soa_total_words <- merge(img_soa_total_non_unique_words, img_soa_total_unique_words, by = c("img_id", "soa"))

theme_set(theme_minimal())
```

```{r, warning=TRUE, message=FALSE, echo = FALSE}

# Descriptive Analysis for ALL images

## Plot: Total number of participants by SOA

ggplot(img_soa_total_subjects, aes(x = factor(soa), y=total_subjects)) +
  geom_boxplot() +
  geom_jitter(width = 0.1) + 
  xlab("SOA") +
  ylab("Total subjects") +
  ggtitle("Unique participants per SOA")

ggsave("analysis-subjects-by-soa.png")

## Plot: Total number of non-unique + unique words by SOA

melt_merge_img_soa_total_words <- melt(merge_img_soa_total_words, id.vars = c("img_id", "soa"), variable.name = "word_type")

p <- ggplot(melt_merge_img_soa_total_words, aes(x = factor(soa), y=value, fill = word_type)) +
  geom_boxplot() +
  #stat_unique(color = "red", show.legend = TRUE) +
  #geom_jitter(width = 0.1) +
  xlab("SOA") +
  ylab("Total number of words") +
  ggtitle("Word count by SOA") +
  theme(legend.title = element_blank())

scale_word_type <- scale_fill_discrete(name = "", labels = c("Non-unique", "Unique"))
p + scale_word_type

ggsave("analysis-word-count-by-soa.png")


```

```{r, warning=TRUE, message=FALSE, echo = FALSE}

# Calculate the KL divergence for each image (based on proportion)

compute_kl <- function(keys, img_dt, soa_vector, probability_colname) {
  word_order <- unique(reorder(img_dt$word, img_dt[[probability_colname]], sum))
  
  img_dt$word <- as.factor(img_dt$word)
  
  soa1 = soa_vector[1]
  soa2 = soa_vector[2]
  
  soa1_list <- merge(img_dt[soa == soa1], data.table(soa = soa1, word = factor(word_order)), by=c("soa", "word"), all=TRUE)[order(match(word, word_order))]
  soa2_list <- merge(img_dt[soa == soa2], data.table(soa = soa2, word = factor(word_order)), by=c("soa", "word"), all=TRUE)[order(match(word, word_order))]
  
  soa1_list[which(is.na(soa1_list[[probability_colname]])), probability_colname] <- 0
  soa2_list[which(is.na(soa2_list[[probability_colname]])), probability_colname] <- 0

  kl_1_2 <- round(KL(rbind(soa1_list[[probability_colname]], soa2_list[[probability_colname]]), test.na = FALSE, unit="log2"), 4)
  return(kl_1_2)
}

compute_pairwise_kl <- function(df, prob_colname) {
  kl_stats_dt <- df[, .(kl_67_133 = compute_kl(.BY, .SD, c("67", "133") , prob_colname),
          kl_67_267 = compute_kl(.BY, .SD, c("67", "267"), prob_colname),
          kl_67_Unlimited = compute_kl(.BY, .SD, c("67", "Unlimited"), prob_colname),
          kl_133_67 = compute_kl(.BY, .SD, c("133", "67"), prob_colname),
          kl_133_267 = compute_kl(.BY, .SD, c("133", "267"), prob_colname),
          kl_133_Unlimited = compute_kl(.BY, .SD, c("133", "Unlimited"), prob_colname),
          kl_267_67 = compute_kl(.BY, .SD, c("267", "67"), prob_colname),
          kl_267_133 = compute_kl(.BY, .SD, c("267", "133"), prob_colname),
          kl_267_Unlimited = compute_kl(.BY, .SD, c("267", "Unlimited"), prob_colname),
          kl_Unlimited_67 = compute_kl(.BY, .SD, c("Unlimited", "67"), prob_colname),
          kl_Unlimited_133 = compute_kl(.BY, .SD, c("Unlimited", "133"), prob_colname),
          kl_Unlimited_267 = compute_kl(.BY, .SD, c("Unlimited", "267"), prob_colname)
          ), by = c("img_id")]
  return(kl_stats_dt)
}

kl_df <- copy(master_raw_df)
kl_df <- kl_df[, .(soa_single_word_freq = sum(frequency)), by = c("img_id", "soa", "word")]
kl_df <- kl_df[, soa_total_words := sum(soa_single_word_freq), by = c("img_id", "soa")]
kl_df <- kl_df[, .(word_soa_proportion = soa_single_word_freq/soa_total_words), by = c("img_id", "soa", "word")]

kl_proportion_stats_dt <- compute_pairwise_kl(kl_df, "word_soa_proportion")
melt_kl_proportion_stats_dt <- melt(kl_proportion_stats_dt, id.vars = "img_id", variable.name = "kl_type", value.name = "kl_value")

word_prop_conf_df <- copy(master_raw_df)
word_prop_conf_df[is.na(confidence)]$confidence <- 1
word_prop_conf_df <- word_prop_conf_df[, .(soa_single_word_freq = sum(frequency), 
                                           soa_single_word_confidence = mean(confidence)
                                           ), 
                                       by = c("img_id", "soa", "word")]
word_prop_conf_df <- word_prop_conf_df[, soa_total_words := sum(soa_single_word_freq), by = c("img_id", "soa")]
word_prop_conf_df <- word_prop_conf_df[, soa_weighted_proportion := (soa_single_word_freq/soa_total_words)*soa_single_word_confidence, by = c("img_id", "soa", "word")]
word_prop_conf_df <- word_prop_conf_df[, soa_total_weighted_proportion := sum(soa_weighted_proportion), by = c("img_id", "soa")]
word_prop_conf_df <- word_prop_conf_df[, .(norm_soa_weighted_proportion = (soa_weighted_proportion/soa_total_weighted_proportion)), by = c("img_id", "soa", "word")]

kl_weighted_pror_stats_dt <- compute_pairwise_kl(word_prop_conf_df, "norm_soa_weighted_proportion")
melt_kl_weighted_pror_stats_dt <- melt(kl_weighted_pror_stats_dt, id.vars = "img_id", variable.name = "kl_type", value.name = "kl_value")

```

```{r, warning=TRUE, message=FALSE, echo = FALSE}

# Plot KL divergence (all images)

plot_kl_divegence <- function(in_dt, title, suffix) {
  
  group_order <- c("kl_67_133", "kl_133_67",
                   "kl_67_267", "kl_267_67",
                   "kl_67_Unlimited", "kl_Unlimited_67",
                   "kl_133_267", "kl_267_133",
                   "kl_133_Unlimited", "kl_Unlimited_133",
                   "kl_267_Unlimited", "kl_Unlimited_267"
                   )
  
  group_label <- c("67-133", "133-67", "67-267", "267-67",
                   "67-Unlimited", "Unlimited-67", "133-267", "267-133",
                   "133-Unlimited", "Unlimited-133", "267-Unlimited", "Unlimited-267")
  
  in_dt <- in_dt[, .(odd_even_group = (which(group_order == lapply(kl_type, as.character))) %% 2 == 0), by = c("img_id", "kl_type", "kl_value")]
  in_dt <- in_dt[, .(from_soa = gsub("kl_(.*)+_{1}.*", "\\1", kl_type),
                                           to_soa = gsub("kl_(.*)_{1}(.*)", "\\2", kl_type)), 
                                       by = c("img_id", "kl_type", "kl_value", "odd_even_group")]
  
  in_dt$kl_type <- factor(in_dt$kl_type, levels=group_order)
  in_dt$from_soa <- factor(in_dt$from_soa, levels=c("67", "133", "267", "Unlimited"))
  in_dt$to_soa <- factor(in_dt$to_soa, levels=c("67", "133", "267", "Unlimited"))
  
  p <- ggplot(in_dt, aes(x = kl_type, y = kl_value, col = odd_even_group)) +
    geom_boxplot(outlier.size = 0) +
    geom_jitter(width = 0.1, size = 1) + 
    ylab("KL Divergence (log2)") +
    ggtitle(paste0(title, " - Pairwise")) +
    scale_x_discrete(name="Group", labels=group_label) +
    theme_light() +
    theme(axis.text.x = element_text(angle = 90), legend.title = element_blank(), legend.position = "none")
  print(p)
  
  ggsave(paste0("analysis-pilot-pairwise-kl-divergence-", suffix, ".png"))
  
  ## Compare against Unlimited
  p <- ggplot(in_dt, aes(x = to_soa, y = kl_value, col = img_id)) +
    geom_boxplot() +
    ylab("KL Divergence (log2)") +
    ggtitle(title) + 
    facet_grid(. ~ from_soa, scales = "free_x") + 
    theme_light() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
  print(p)
  
  ggsave(paste0("analysis-pilot-approx-kl-divergence-", suffix, ".png"))
}

plot_kl_divegence(melt_kl_proportion_stats_dt, "KL Divergence (Proportion)", "proportion")
plot_kl_divegence(melt_kl_weighted_pror_stats_dt, "KL Divergence (Weighted Proportion)", "weighted")

# KL(rbind(
#   melt_kl_proportion_stats_dt$kl_value/sum(melt_kl_proportion_stats_dt$kl_value), 
#   melt_kl_weighted_pror_stats_dt$kl_value/sum(melt_kl_weighted_pror_stats_dt$kl_value)), 
#   test.na = FALSE, unit="log2")
# 
ggplot(data.table(melt_kl_weighted_pror_stats_dt$kl_value/sum(melt_kl_weighted_pror_stats_dt$kl_value)), aes(x=V1)) + geom_bar()
```


```{r, warning=TRUE, message=FALSE, echo = FALSE}
# Function - Perform single image analysis and generate plots
analyse_plot_single_image <- function(master_df, imgid) {
  dfi <- master_df[img_id == imgid]
  label_67 <- paste0("67ms (N=", img_soa_total_subjects[img_id == imgid & soa == "67"]$total_subjects, ",W=", img_soa_total_non_unique_words[img_id == imgid & soa == "67"]$total_words, ")")
  label_133 <- paste0("67ms (N=", img_soa_total_subjects[img_id == imgid & soa == "133"]$total_subjects,",W=", img_soa_total_non_unique_words[img_id == imgid & soa == "133"]$total_words, ")")
  label_267 <- paste0("67ms (N=", img_soa_total_subjects[img_id == imgid & soa == "267"]$total_subjects,",W=", img_soa_total_non_unique_words[img_id == imgid & soa == "267"]$total_words, ")")
  label_Unlimited <- paste0("67ms (N=", img_soa_total_subjects[img_id == imgid & soa == "Unlimited"]$total_subjects,",W=", img_soa_total_non_unique_words[img_id == imgid & soa == "Unlimited"]$total_words, ")")
  
  soa_labeller <- function(variable, value) {
    soa_labels <- c()
    for (single_soa in value) {
      total_subjects <- img_soa_total_subjects[img_id == imgid & soa == single_soa]$total_subjects[1]
      total_words <- img_soa_total_non_unique_words[img_id == imgid & soa == single_soa]$total_words[1]
      soa_labels <- rbind(soa_labels, paste0(single_soa, " (N=", total_subjects, ",W=", total_words, ")"))
    }
    return(soa_labels)
  }
  
  p <- ggplot(melt_merge_img_soa_total_words[img_id == imgid], aes(x=as.numeric(factor(soa)), y=value, col=word_type)) +
    geom_point() +
    geom_line(stat = "identity") +
    ggtitleimg("Word count per SOA", imgid) +
    scale_x_discrete(name="SOA", labels=c("67", "133", "267", "Unlimited")) +
    scale_y_continuous(name = "Word count") +
    theme(legend.title = element_blank())
  
  x_range <- ggplot_build(p)$layout$panel_params[[1]]$x.range
  y_range <- ggplot_build(p)$layout$panel_params[[1]]$y.range
  
  image <- image_scale(get_image_by_id(nishimoto_images_folder, imgid), "200")
  
  print(
    p + annotation_custom(rasterGrob(image, interpolate = FALSE), 
                        xmin = x_range[2], xmax = x_range[2] + 2, ymin = y_range[2] - 10, ymax = y_range[2])  +
    coord_cartesian(clip = 'off') +
    theme(plot.margin = unit(c(1,3,1,1), "lines"))
  )
  
  ggsave(paste0("word_count_per_soa_img_", imgid, '.png'))
  
  ## Plot: Word frequency by SOA (Individual Image)
  
  p <- ggplot(dfi) + 
    geom_histogram(stat = "identity") +
    aes(x=reorder(dfi$word, dfi$frequency, sum), y=1, col=soa, fill = soa) +
    coord_flip() +
    ggtitleimg("Word frequency distribution by SOA", imgid) +
    xlab("Word") + 
    ylab("Count") +
    theme(axis.text.y = element_text(size = 3)) +
    facet_grid(. ~ soa, labeller = soa_labeller) 
  
  max_count <- max(dfi[, sum(frequency), by = c("soa", "word")]$V1)
  print(
    p + scale_y_continuous(breaks = seq(0, max_count, by=2))
  )
  
  ggsave(paste0("ind_word_freq_dist_per_soa_img_", imgid, '.png'))
  
  ## Plot: Word proportion by SOA (Individual Image)
  word_prop_df <- copy(dfi)
  word_prop_df <- word_prop_df[, .(soa_single_word_freq = sum(frequency)), by = c("img_id", "soa", "word")]
  word_prop_df <- word_prop_df[, soa_total_words := sum(soa_single_word_freq), by = c("img_id", "soa")]
  word_prop_df <- word_prop_df[, .(word_soa_proportion = soa_single_word_freq/soa_total_words), by = c("img_id", "soa", "word")]
    
  p <- ggplot(word_prop_df) + 
    geom_histogram(stat = "identity") +
    aes(x=reorder(word_prop_df$word, word_prop_df$word_soa_proportion, sum), y=word_soa_proportion, col=soa, fill = soa) +
    coord_flip() +
    ggtitleimg("Word proportion distribution by SOA", imgid) +
    xlab("Word") + 
    ylab("Proportion") +
    theme(axis.text.y = element_text(size = 3)) +
    facet_grid(. ~ soa, labeller = soa_labeller) 
  
  max_count <- max(word_prop_df[, word_soa_proportion, by = c("soa", "word")]$word_soa_proportion)
  print(
    p + scale_y_continuous(breaks = seq(0, max_count, by=0.05)) +
    theme(axis.text.x = element_text(size = 5))
  )
  
  ggsave(paste0("ind_word_proportion_dist_per_soa_img_", imgid, '.png'))

  ## Plot: Word proportion weighted with mean confidence by SOA (Individual Image)
  word_prop_conf_df <- copy(dfi)
  
  ### Unlimited SOA has no confidence [ASSUMPTION]
  word_prop_conf_df[is.na(confidence)]$confidence <- 1
  word_prop_conf_df <- word_prop_conf_df[, .(soa_single_word_freq = sum(frequency), 
                                             soa_single_word_confidence = mean(confidence)
                                             ), 
                                         by = c("img_id", "soa", "word")]
  word_prop_conf_df <- word_prop_conf_df[, soa_total_words := sum(soa_single_word_freq), by = c("img_id", "soa")]
  word_prop_conf_df <- word_prop_conf_df[, soa_weighted_proportion := (soa_single_word_freq/soa_total_words)*soa_single_word_confidence, by = c("img_id", "soa", "word")]
  word_prop_conf_df <- word_prop_conf_df[, soa_total_weighted_proportion := sum(soa_weighted_proportion), by = c("img_id", "soa")]
  word_prop_conf_df <- word_prop_conf_df[, .(norm_soa_weighted_proportion = (soa_weighted_proportion/soa_total_weighted_proportion)), by = c("img_id", "soa", "word")]
  
  p <- ggplot(word_prop_conf_df) + 
    geom_histogram(stat = "identity") +
    aes(x=reorder(word_prop_conf_df$word, word_prop_conf_df$norm_soa_weighted_proportion, sum), y=norm_soa_weighted_proportion, col=soa, fill = soa) +
    coord_flip() +
    ggtitleimg("Word confidence-weighted proportion distribution by SOA", imgid) +
    xlab("Word") + 
    ylab("Proportion") +
    theme(axis.text.y = element_text(size = 3)) +
    facet_grid(. ~ soa, labeller = soa_labeller) 
  
  max_count <- max(word_prop_conf_df[, norm_soa_weighted_proportion, by = c("soa", "word")]$norm_soa_weighted_proportion)
  print(
    p + scale_y_continuous(breaks = seq(0, max_count, by=0.05)) +
    theme(axis.text.x = element_text(size = 5))
  )
  
  ggsave(paste0("ind_word_weighted_proportion_dist_per_soa_img_", imgid, '.png'))
}
```

```{r, warning=FALSE, message=FALSE, echo = FALSE, results="asis"}
# Plot single image analysis
analyse_plot_single_image(master_raw_df, 9)
```

```{r plot-kl-function, warning=FALSE, message=FALSE, echo = FALSE}
plot_KL <- function(aggregate_result, imgid, soa1, soa2) {
   
  t1_wide <- aggregate_result$t1_wide
  t1_melt <- aggregate_result$t1_melt
  word_cols <- aggregate_result$word_cols
  
  soa_list <- unique(t1_wide$soa)
  soa_index_1 <- which(soa_list == soa1)
  soa_index_2 <- which(soa_list == soa2)
  
  mat_1_2 <- as.matrix(rbind(as.vector(subset(t1_wide[soa_index_1,], select=word_cols)), 
           as.vector(subset(t1_wide[soa_index_2,], select=word_cols))))
  mat_2_1 <- as.matrix(rbind(as.vector(subset(t1_wide[soa_index_2,], select=word_cols)), 
           as.vector(subset(t1_wide[soa_index_1,], select=word_cols))))
  
  kl1 <- paste0("KL(", soa1, ",", soa2, ")=", round(KL(mat_1_2, test.na = FALSE, unit="log2"), 4))
  kl2 <- paste0("KL(", soa2, ",", soa1, ")=",round(KL(mat_2_1, test.na = FALSE, unit="log2"), 4))
  
  t_1_2 <- t1_melt[soa %in% c(soa1, soa2)]
  max_y <- max(t_1_2$value)
  p1 <- ggplot(t_1_2, aes(x = variable, y = value, label = soa)) +
    geom_bar(stat = 'identity', aes(fill = soa), width = .5) +
    coord_flip() +
    theme_bw() +
    ggtitle(paste0("Image: ", imgid, ' - ', kl1, ', ', kl2, sep=", ")) + 
    theme(axis.text.y = element_text(size=3), legend.position = "top") + xlab("") 

  print(p1)
  #ggsave(paste0("kl-words-", imgid, "-", soa1, "-", soa2, ".png"), plot = p1, scale = 4)

  cat("\n")
  cat("\n")
}

```


```{r, warning=FALSE, message=TRUE, echo = FALSE}
as.image_id <- function(imgstr) {
  return (as.integer(gsub("im[0]+([1-9][0-9]*).jpg", "\\1", imgstr)))
}

aggregate_image_word <- function(df, alon_df, imgstr) {
  imgid <- as.image_id(imgstr)
  
  all_df <- df
  
  t1 <- all_df[img == imgstr, c("img_id", "soa", "word", "frequency")]
  t1 <- rbind(t1, alon_df[img_id == imgid, c("img_id", "soa", "word", "frequency")]) 
  t1 <- t1[, `:=`(probability = frequency/sum(frequency)), by = soa]
  
  t1$soa <- as.factor(t1$soa)
  t1[frequency == 1, frequency_one := TRUE]
  t1[frequency > 1, frequency_one := FALSE]
  
  t1_f <- dcast(t1, formula = img_id+soa ~ word, value.var = c("frequency"))
  t1_f[is.na(t1_f)] <- 0
  
  t1_wide <- dcast(t1, formula = soa ~ word, value.var = c("probability"), fill = 0)
  p_67 = t1_wide[soa == "67"]
  
  word_cols <- colnames(t1_wide)
  word_cols <- word_cols[word_cols != 'soa']
  
  t1_melt <- melt(t1_wide, id.vars = c("soa"), measure.vars = word_cols)
  t1_melt <- merge(t1_melt, t1[,c("soa", "word", "frequency_one")], by.x = c("soa", "variable"), by.y = c("soa", "word"), all = TRUE)
  t1_melt <- t1_melt[order(-value)]
  t1_melt$variable <- factor(t1_melt$variable, levels = rev(unique(t1_melt$variable)))
  t1_melt[frequency_one == TRUE, c("value") := value * -1]
  
  p <- ggplot(t1_melt, aes(x = variable, y = value, label = value)) + 
    #geom_histogram(alpha = 0.3, position = "identity", stat = "identity") + 
    #geom_area(alpha = 0.2, size = 1) + 
    geom_bar(stat = 'identity', aes(fill = soa), width = .5) + 
    ggtitle(paste0("Image: ", imgid)) + 
    coord_flip() +
    #scale_y_continuous(expand = c(0, 0)) +
    theme_bw() + 
    theme(axis.text.y = element_text(size=3), legend.position = "top") + xlab("")
  print(p)
  ggsave(paste0("agg-words-", imgid, ".png"), plot = p, scale = 4)
    # Calculate entropy
  t1_melt[, `:=`(log_value = value * log2(value))]
  t1_melt[is.na(t1_melt)] <- 0
    
  cat(paste0("Entropy for Unlimited: ", round(sum(t1_melt[soa == 'Unlimited']$log_value)*-1, 4), "\n"))
  cat(paste0("Entropy for 67ms: ", round(sum(t1_melt[soa == 67]$log_value)*-1, 4), "\n"))
  cat(paste0("Entropy for 133ms: ", round(sum(t1_melt[soa == 133]$log_value)*-1, 4), "\n"))
  cat(paste0("Entropy for 267ms: ", round(sum(t1_melt[soa == 267]$log_value)*-1, 4), "\n"))
  
  return(list("t1_wide" = t1_wide, "t1_melt"= t1_melt, "word_cols" = word_cols))
}
```

```{r test-only, warning=TRUE, message=FALSE, echo = FALSE, include = FALSE}
# img_list <- c("im0000003.jpg", "im0000009.jpg", "im0000014.jpg")
# 
# for (i in 1:length(img_list)) {
#   img <- img_list[i]
#   img_id <- as.image_id(img)
# 
#   aggregate_result <- aggregate_image_word(all_df, alon_img_desc, img)
#   plot_KL(aggregate_result, img_id, "Unlimited", "67")
#   plot_KL(aggregate_result, img_id, "Unlimited", "133")
#   plot_KL(aggregate_result, img_id, "Unlimited", "267")
#   plot_KL(aggregate_result, img_id, "67", "133")
#   plot_KL(aggregate_result, img_id, "67", "267")
#   plot_KL(aggregate_result, img_id, "133", "267")
# }

```



