---
title: "Analysis"
subtitle: "MTurk Analysis - `r format(Sys.time(), '%d %B, %Y')`"
geometry: left=2cm,right=2cm,top=2cm,bottom=2cm
output:
  pdf_document:
    latex_engine: xelatex
  html_document:
    df_print: paged
header-includes: \usepackage{xcolor}
---

```{r include=FALSE, echo=FALSE, message=FALSE}
source('embed_import_libraries.R')
# source('embed_configuration.R')

# Functions
# source('function-analyse_single_image_kl_divergence.R')
# source('function-analyse_plot_single_image.R')
# source('function-aggregate_word_column.R')
# source('function-calculate_kl_for_dataframe.R')
# source('function-compute_kl.R')
# source('function-compute_pairwise_kl.R')
# source('function-image_utilities.R')
# source('function-load_alon_descriptors.R')
# source('function-load_data.R')
# source('function-load_subject_data.R')
# source('function-plot_kl_divergence.R')
# source('function-plot_word_cloud.R')
# source('function-utilities.R')
# source('function-validate_img_soa_group_numbers.R')

library("scales")
library("grid")
library("gridExtra")
```

```{r}
## Data Summary

load(file = "psy4100_master_data.RData")

print(paste0("Total participants (includes Shinji's): ", total_subjects))
print(paste0("Total participants (only MTurk): ", total_mturk_subjects))
print(paste0("Total images (including 3 practice images):", length(included_img_ids)))

# Function

add_image_to_plot <- function(plt, img) {
  q1 <- ggplot() + annotation_custom(rasterGrob(img, interpolate = FALSE))
  
  p2 <- ggplotGrob(plt)
  q2 <- ggplotGrob(q1)
  
  gt <- gtable(widths = unit(c(1, 1, .4), "null"), heights = unit(c(.8, 1, 1), "null"))
  gt <- gtable_add_grob(gt, p2, t = 1, b = 3, l = 1, r = 3)
  gt <- gtable_add_grob(gt, q2, t = 1, l = 3)

  return(gt)
}

master_df <- master_raw_stem_df[soa != "Unlimited", ]

# This is to replace the stem words with hyphen with the original.
master_df[stem_word %like% "-,", stem_word := word ] 
master_df[stem_word %like% ", -", stem_word := word ] 
master_df[stem_word %like% "-, ", stem_word := word ]

all_image_ids <- unique(master_df$img_id)
```

```{r, message=FALSE}

# Ignore  practice images
master_df <- master_df[!img_id %in% c(3, 9, 14)]
img_soa_subject <- master_df[, .(subject_count = length(unique(.SD$subject))), by=c("img_id", "soa")]

calculate_ia_by_cr <- function(img_df, target_img_id, plot_figure = FALSE) {
  all_img_cr_intra <- data.table()
  all_img_cr_inter <- data.table()

  unique_words <- unique(img_df$stem_word)
  
  for (i in 1:length(unique_words)) {
    target_word <- unique_words[i]
    
    # Calculate intra-agreement
    word_df <- master_df[img_id == target_img_id & stem_word == target_word, 
                         .(mean_confidence = mean(confidence), word_count = .N), by=c("img_id", "soa", "stem_word")]
    word_df <- merge(word_df, img_soa_subject, by = c("img_id", "soa"), all.x = TRUE)
    all_img_cr_intra <- rbind(all_img_cr_intra, word_df)
    
    # Calculate inter-agreement
    word_other_df <- master_df[img_id != target_img_id & stem_word == target_word, .(mean_other_confidence = mean(confidence), word_count = .N), by=c("img_id", "soa", "stem_word")]
    word_other_df <- merge(word_other_df, img_soa_subject, by = c("img_id", "soa"), all.x = TRUE)
    all_img_cr_inter <- rbind(all_img_cr_inter, word_other_df)
  }
  
  all_img_cr_intra$cr_intra <- all_img_cr_intra$word_count/all_img_cr_intra$subject_count
  all_img_cr_intra$cr_intra_weighted <- (all_img_cr_intra$word_count/all_img_cr_intra$subject_count)*all_img_cr_intra$mean_confidence
  all_img_cr_inter$cr_inter <- all_img_cr_inter$word_count/all_img_cr_inter$subject_count
  all_img_cr_inter$cr_inter_weighted <- (all_img_cr_inter$word_count/all_img_cr_inter$subject_count)*all_img_cr_inter$mean_other_confidence
  
  all_img_cr_mean_inter <- all_img_cr_inter[, .(mean_cr_inter = mean(cr_inter), mean_cr_inter_weighted = mean(cr_inter_weighted)), by=c("soa", "stem_word")]
  
  all_img_ia = merge(all_img_cr_intra, all_img_cr_mean_inter, by=c("stem_word", "soa"), all.x = TRUE)
  all_img_ia[is.na(mean_cr_inter), ]$mean_cr_inter <- 0
  all_img_ia[is.na(mean_cr_inter_weighted), ]$mean_cr_inter_weighted <- 0
  
  all_img_ia$ia <- all_img_ia$cr_intra - all_img_ia$mean_cr_inter
  all_img_ia$ia_weighted <- all_img_ia$cr_intra_weighted - all_img_ia$mean_cr_inter_weighted
  
  if (plot_figure) {
    m_df <- melt(all_img_ia, id.vars = c("stem_word", "soa", "type"), measure.vars = c("cr_intra", "mean_cr_inter"))
    
    gg1<- ggplot(m_df[type == 'specific', ], aes(x=reorder(stem_word, -value), y=value, color=variable)) +
      geom_point(size=3) +
      scale_color_discrete(labels=c("CR(w,Y)","CR(w, -)")) +
      xlab("Word") +
      ylab("Value") +
      theme_bw() +
      theme(text = element_text(size=20), axis.text.x = element_text(angle = 90, vjust = 0.3)) + 
      facet_grid(rows = vars(soa))
    
    gg2<- ggplot(m_df[type == 'general', ], aes(x=reorder(stem_word, -value), y=value, color=variable)) +
      geom_point(size=3) +
      scale_color_discrete(labels=c("CR(w,Y)","CR(w, -)")) +
      xlab("Word") +
      ylab("Value") +
      theme_bw() +
      theme(text = element_text(size=20), axis.text.x = element_text(angle = 90, vjust = 0.3)) + 
      facet_grid(rows = vars(soa))
    
    h <- 8
    ar <- 2.5
      
    ggsave(gg1, height=h, width= h*ar, filename = paste0("ia_cr_", target_img_id, "_specific.png"))
    ggsave(gg2, height=h, width= h*ar, filename = paste0("ia_cr_", target_img_id, "_general.png"))
    
    print(sprintf("Mean IA [67=%.4f, 133=%.4f, 267=%.4f]", 
                  mean(all_img_ia[img_id == target_img_id & soa == 67, ]$ia), 
                  mean(all_img_ia[img_id == target_img_id & soa == 133, ]$ia),
                  mean(all_img_ia[img_id == target_img_id & soa == 267, ]$ia)
    ))
  }
  
  return (all_img_ia)
}

all_ia_cr <- data.table()
target_image_ids <- all_image_ids[which(!all_image_ids %in% c(3, 9, 14))]

target_image_ids <- c(63)
for (target_img_id in target_image_ids) {
  #target_img_id = 2277 # Eiffel tower
  img_df <- master_df[img_id == target_img_id, ]
  all_ia_cr <- rbind(all_ia_cr, calculate_ia_by_cr(img_df, target_img_id, plot_figure = FALSE))
  print(sprintf("Completed image %s...", target_img_id))
}


```


```{r, }
load('all_img_type1auc.RData')

# Calculate the stem_word + img_id + count
word_img_count_df <- data.table()

for (idx in 1:length(all_image_ids)) {
  img_id <- all_image_ids[idx]
  cur_image_df <- all_image_dfs[[idx]]

  word_img_count_df <- rbind(word_img_count_df, cur_image_df[, .(word_count = .N, mean_confidence = mean(.SD$confidence)), by=c("img_id", "soa", "stem_word")])
}

all_img_type1auc <- all_img_type1auc[type1auc > 0.5, ]
all_img_type1auc_subject <- all_img_type1auc

all_img_type1auc <- all_img_type1auc[, .(avg_type1auc = mean(type1auc), avg_type1auc_weighted = mean(type1auc_weighted)), by=c("stem_word", "soa", "img_id")]
all_img_type1auc$soa <- factor(all_img_type1auc$soa)
all_df <- merge(all_img_type1auc, word_img_count_df, all = FALSE)

mean_img_type1auc <- all_df[, .(auc = mean(avg_type1auc*word_count)), by=c("img_id", "soa")]
mean_img_type1auc_weighted <- all_df[, .(auc = mean(avg_type1auc_weighted*word_count)), by=c("img_id", "soa")]
all_mean <- mean_img_type1auc[,.(mean_auc=mean(auc)),by=c("soa")]

ggplot(mean_img_type1auc, aes(x=auc, by=c("soa"))) +
  geom_histogram() +
  facet_grid( . ~ soa) +
  xlab("Mean AUC (non-weighted)")

dodge <- position_dodge(width = 0.8)
ggplot(mean_img_type1auc, aes(x=soa, y=auc)) +
  geom_violin(position = dodge) +
  geom_boxplot(width=0.3, position = dodge) +
  ylab("Mean AUC (non_weighted)")

all_img_ia <- all_df[, .(ia = sum(2*(.SD$avg_type1auc-0.5)*word_count)), by=c("img_id", "soa")]
ggplot(all_img_ia, aes(x=ia, by=c("soa"))) +
  geom_histogram() +
  facet_grid( . ~ soa) +
  xlab("Intersubjective Agreement")

dodge <- position_dodge(width = 0.8)
ggplot(all_img_ia, aes(x=soa, y=ia)) +
  geom_violin(position = dodge) +
  geom_boxplot(width=0.3, position = dodge) + 
  ylab("Intersubjective Agreement")

# Confidence weighted

mean_img_type1auc_weighted <- all_df[, .(auc = mean(avg_type1auc_weighted*word_count)), by=c("img_id", "soa")]

ggplot(mean_img_type1auc_weighted, aes(x=auc, by=c("soa"))) +
  geom_histogram() +
  facet_grid( . ~ soa) +
  xlab("Mean AUC (confidence-weighted)")

dodge <- position_dodge(width = 0.8)
ggplot(mean_img_type1auc_weighted, aes(x=soa, y=auc)) +
  geom_violin(position = dodge) +
  geom_boxplot(width=0.3, position = dodge) +
  ylab("Mean AUC (confidence-weighted)")

all_img_ia <- all_df[, .(ia = sum(2*(.SD$avg_type1auc_weighted-0.5)*word_count)), by=c("img_id", "soa")]
ggplot(all_img_ia, aes(x=ia, by=c("soa"))) +
  geom_histogram() +
  facet_grid( . ~ soa) +
  xlab("Intersubjective Agreement")

dodge <- position_dodge(width = 0.8)
ggplot(all_img_ia, aes(x=soa, y=ia)) +
  geom_violin(position = dodge) +
  geom_boxplot(width=0.3, position = dodge) + 
  ylab("Intersubjective Agreement")
```

```{r }
load('all_ia_cr.RData')

ggplot(all_ia_cr, aes(x=ia)) +
  geom_histogram() +
  facet_grid(. ~ soa) + 
  ggtitle("IA distribution by SOA")

ggplot(all_ia_cr, aes(x=soa, y=ia)) +
  geom_boxplot() +
  ggtitle("IA distribution by SOA")

ggplot(all_ia_cr, aes(x=scale(ia))) +
  geom_histogram() +
  facet_grid(. ~ soa) + 
  ggtitle("z-score(IA) distribution by SOA")

ggplot(all_ia_cr, aes(x="", y=scale(ia))) +
  geom_boxplot() +
  facet_grid(. ~ soa) +
  ggtitle("z-score(IA) distribution by SOA")

all_ia_cr$type <- ifelse(all_ia_cr$ia > 0, "specific", "general")
all_word_type <- all_ia_cr[, .(general_count=nrow(.SD[type == 'general', ]), specific_count=nrow(.SD[type == 'specific', ])), by=c("img_id", "soa")]
all_word_type <- melt(all_word_type, id.vars = c("img_id", "soa"), measure.vars = c("general_count", "specific_count"))

img_ids <- unique(all_word_type$img_id)
img_ids_df <- data.table(img_id = img_ids, img_idx = 1:length(img_ids))
all_word_type <- merge(all_word_type, img_ids_df, by="img_id", all.x = TRUE)

wt_df <- all_word_type[, .(mean_count = mean(value)), by=c("soa", "variable")]
ggplot(data=wt_df, aes(x=soa, y=mean_count, colour=variable)) +
  geom_point(size=5) +
  geom_smooth(aes(x=as.numeric(soa), y=mean_count), method="glm", se=FALSE) +
  ggtitle("IA > 0 is specific; IA <= 0 is general") + 
  ylab("Mean word occurrence") +
  scale_color_discrete(labels=c("IA <= 0", "IA > 0"))
```

```{r }
load('all_ia_cr.RData')

ia_cr_67 <- all_ia_cr[soa == 67, .(ia), by=c("stem_word", "soa", "img_id")]
ia_cr_67$scale_ia <- scale(ia_cr_67$ia)

ia_cr_133 <- all_ia_cr[soa == 133, .(ia), by=c("stem_word", "soa", "img_id")]
ia_cr_133$scale_ia <- scale(ia_cr_133$ia)

ia_cr_267 <- all_ia_cr[soa == 267, .(ia), by=c("stem_word", "soa", "img_id")]
ia_cr_267$scale_ia <- scale(ia_cr_267$ia)

ia_cr_scale <- rbind(ia_cr_67, ia_cr_133, ia_cr_267)

all_ia_cr <- merge(all_ia_cr, ia_cr_scale, by=c("stem_word", "soa", "img_id"), all.x=TRUE)

all_ia_cr$type <- ifelse(all_ia_cr$scale_ia > 0, "specific", "general")
all_word_type <- all_ia_cr[, .(general_count=nrow(.SD[type == 'general', ]), specific_count=nrow(.SD[type == 'specific', ])), by=c("img_id", "soa")]
all_word_type <- melt(all_word_type, id.vars = c("img_id", "soa"), measure.vars = c("general_count", "specific_count"))

img_ids <- unique(all_word_type$img_id)
img_ids_df <- data.table(img_id = img_ids, img_idx = 1:length(img_ids))
all_word_type <- merge(all_word_type, img_ids_df, by="img_id", all.x = TRUE)

wt_df <- all_word_type[, .(mean_count = mean(value)), by=c("soa", "variable")]
ggplot(data=wt_df, aes(x=soa, y=mean_count, colour=variable)) +
  geom_point(size=5) +
  geom_smooth(aes(x=as.numeric(soa), y=mean_count), method="glm", se=FALSE) +
  ggtitle("z-score(IA) > 0 is specific; z-score(IA) <= 0 is general") + 
  ylab("Mean word occurrence") +
  scale_color_discrete(labels=c("z-score(IA) <= 0", "z-score(IA) > 0"))
```

```{r }
load('all_ia_cr.RData')

ia_cr_67 <- all_ia_cr[soa == 67, .(ia), by=c("stem_word", "soa", "img_id")]
ia_cr_67$scale_ia <- scale(ia_cr_67$ia)

ia_cr_133 <- all_ia_cr[soa == 133, .(ia), by=c("stem_word", "soa", "img_id")]
ia_cr_133$scale_ia <- scale(ia_cr_133$ia)

ia_cr_267 <- all_ia_cr[soa == 267, .(ia), by=c("stem_word", "soa", "img_id")]
ia_cr_267$scale_ia <- scale(ia_cr_267$ia)

ia_cr_scale <- rbind(ia_cr_67, ia_cr_133, ia_cr_267)

all_ia_cr <- merge(all_ia_cr, ia_cr_scale[,.(scale_ia), by=c("stem_word", "soa", "img_id")], by=c("stem_word", "soa", "img_id"), all.x=TRUE)

determine_word_type <- function(soa, quan_67, quan_133, quan_267, ia) {
  if (soa == 67) {
    q <- quan_67
  } else if (soa == 133) {
    q <- quan_133
  } else if (soa == 267) {
    q <- quan_267
  }
  
  if (ia <= as.numeric(q["5%"])) {
    return ("general")
  } else if (ia >= as.numeric(q["95%"])) {
    return ("specific")
  } else {
    return ("neutral")
  }
}

q_67 <- quantile(all_ia_cr[soa == 67, ]$ia, c(0, 0.05, 0.25, 0.5, 0.75, 0.95, 1.0))
q_133 <- quantile(all_ia_cr[soa == 133, ]$ia, c(0, 0.05, 0.25, 0.5, 0.75, 0.95, 1.0))
q_267 <- quantile(all_ia_cr[soa == 267, ]$ia, c(0, 0.05, 0.25, 0.5, 0.75, 0.95, 1.0))

all_word_type <- all_ia_cr[, .(type = determine_word_type(soa, q_67, q_133, q_267, ia)), by=c("stem_word", "img_id", "soa", "mean_confidence", "word_count", "subject_count", "ia", "ia_weighted")]
all_word_type <- all_word_type[type != "neutral", .(general_count=nrow(.SD[type == 'general', ]), specific_count=nrow(.SD[type == 'specific', ])), by=c("img_id", "soa")]
all_word_type <- melt(all_word_type, id.vars = c("img_id", "soa"), measure.vars = c("general_count", "specific_count"))

img_ids <- unique(all_word_type$img_id)
img_ids_df <- data.table(img_id = img_ids, img_idx = 1:length(img_ids))
all_word_type <- merge(all_word_type, img_ids_df, by="img_id", all.x = TRUE)

wt_df <- all_word_type[, .(mean_count = mean(value)), by=c("soa", "variable")]
ggplot(data=wt_df, aes(x=soa, y=mean_count, colour=variable)) +
  geom_point(size=5) +
  geom_smooth(aes(x=as.numeric(soa), y=mean_count), method="glm", se=FALSE) +
  ylab("Mean word occurrence") +
  ggtitle("Using 5% (general) and 95% (specific) percentiles of IA")
  #scale_color_discrete(labels=c("IA <= 0", "IA > 0"))


```

```{r }
```
  
```{r, }

# Non-confidence weighted
ggplot(avg_ia_cr, aes(x=avg_ia, by=c("soa"))) +
  geom_histogram() +
  facet_grid( . ~ soa) +
  xlab("Intersubjective Agreement")

dodge <- position_dodge(width = 0.8)
ggplot(avg_ia_cr, aes(x=soa, y=avg_ia)) +
  geom_violin(position = dodge) +
  geom_boxplot(width=0.3, position = dodge) + 
  ylab("Intersubjective Agreement")

# Confidence weighted
all_img_weighted_ia_cr <- all_ia_cr[ia > 0, .(ia = mean(ia_weighted)), by=c("img_id", "soa")]

ggplot(all_img_weighted_ia_cr, aes(x=ia, by=c("soa"))) +
  geom_histogram() +
  facet_grid( . ~ soa) +
  xlab("Confidence-weighted Intersubjective Agreement")

dodge <- position_dodge(width = 0.8)
ggplot(all_img_weighted_ia_cr, aes(x=soa, y=ia)) +
  geom_violin(position = dodge) +
  geom_boxplot(width=0.3, position = dodge) + 
  ylab("Confidence-weighted Intersubjective Agreement")

all_img_ia=all_ia_cr[ia_weighted > 0, ]
all_img_ia$ia = all_img_ia$ia_weighted
```


```{r, }
# Top 10
top_ia = head(all_img_ia[,.(ia = mean(ia)), by=c("img_id")][order(-ia)], 10)
bottom_ia = head(all_img_ia[,.(ia = mean(ia)), by=c("img_id")][order(ia)], 10)

top_ia_67 = head(all_img_ia[soa == 67,][order(-ia)], 10)
top_ia_133 = head(all_img_ia[soa == 133,][order(-ia)], 10)
top_ia_267 = head(all_img_ia[soa == 267,][order(-ia)], 10)

bottom_ia_67 = head(all_img_ia[soa == 67,][order(ia)], 10)
bottom_ia_133 = head(all_img_ia[soa == 133,][order(ia)], 10)
bottom_ia_267 = head(all_img_ia[soa == 267,][order(ia)], 10)
```

```{r, }
posx <- 0
posy <- 100

p <- ggplot(data.frame()) + geom_point() + 
  xlim(0, 100) + ylim(0, 100) +
  theme(axis.text = element_blank())
  
target_df <- bottom_ia_267

for (i in 1:nrow(target_df)) {
  img_id <- target_df[i, ]$img_id
  
  p <- p + annotation_raster(get_image_by_id(nishimoto_images_folder, img_id), ymin = posy, ymax=posy - 20, xmin=posx, xmax=posx + 30)
      
  posy <- posy - 20
    
  if (posx >=100) {
    posx <- 0
  }
  
  if (posy <= 0) {
    posy <- 100
    posx <- posx + 30
  }
}

ggsave(paste0('test', as.String(i), '.png'))


```





