options(knitr.table.format = 'markdown')

library(car)
library(cowplot)
library(data.table)
library(dplyr)
#library(entropy)
library(ggplot2)
library(ggpubr)
library(ggwordcloud)
library(grid)
library(gtable)
library(jpeg)
library(kableExtra)
library(knitr)
library(lme4)
library(lsr)
library(magick)
library(multcomp)
library(nlme)
library(philentropy)
library(psych)
library(pwr)
library(rlist)
library(simr)
library(textstem)
library(tidyverse)
library(tidyr)
library(wordcloud2)

# This is for the word cloud
library("tm")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")
