options(knitr.table.format = 'markdown')

usePackage <- function(p) {
    if (!is.element(p, installed.packages()[,1]))
        install.packages(p, dep = TRUE)
    require(p, character.only = TRUE)
}

usePackage('car')
usePackage('cowplot')
usePackage('data.table')
usePackage('dplyr')
#library('entropy')
usePackage('ggplot2')
usePackage('ggpubr')
usePackage('ggwordcloud')
usePackage('grid')
usePackage('gtable')
usePackage('jpeg')
usePackage('kableExtra')
usePackage('knitr')
usePackage('lme4')
usePackage('lsr')
usePackage('magick')
usePackage('multcomp')
usePackage('nlme')
usePackage('philentropy')
usePackage('psych')
usePackage('pwr')
usePackage('rlist')
usePackage('scales')
usePackage('simr')
usePackage('stringr')
usePackage('textstem')
usePackage('tidyverse')
usePackage('tidyr')
usePackage('wordcloud2')

# This is for the word cloud
usePackage("tm")
usePackage("SnowballC")
usePackage("wordcloud")
usePackage("RColorBrewer")
